{ inputs, pkgs, ... }:
let
  pkgs-unstable = inputs.nixpkgs-unstable.legacyPackages.${pkgs.system};
in
{
  services.cloudflared = {
    package = pkgs-unstable.cloudflared;
    enable = true;
    tunnels = {
      # all the ingress are managed in cf dashboard
      rpi = {
        # generated by `cloudflared tunnel create`
        credentialsFile = "/etc/cloudflared/credential.json";
        # generated by `cloudflared login`
        certificateFile = "/etc/cloudflared/cert.pem";
        default = "http_status:404";
      };
    };
  };

  # quic-go need larger udp buffer size
  # https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
  boot.kernel.sysctl = {
    "net.core.rmem_max" = 7500000;
    "net.core.wmem_max" = 7500000;
  };

}
