{ pkgs, ... }:
{
  services.garage = {
    enable = true;
    # pin to v1.2.0 due to https://git.deuxfleurs.fr/Deuxfleurs/garage/issues/1084
    package = pkgs.garage_1_2_0;
    extraEnvironment = {
      GARAGE_ALLOW_WORLD_READABLE_SECRETS = "true";
    };
    settings = {
      replication_factor = 1;
      rpc_bind_addr = "[::]:3901";
      # generated by `openssl rand -hex 32 | sudo tee /var/lib/garage/rpc-secret`
      # and change the permission by `sudo chmod 0755 /var/lib/garage/rpc-secret`
      rpc_secret_file = "/var/lib/garage/rpc-secret";
      s3_api = {
        api_bind_addr = "[::]:3900";
        s3_region = "garage";
      };
      lmdb_map_size = "4G";
    };
  };
  networking = {
    firewall.allowedTCPPorts = [ 3900 ];
  };

}
